# Using Docker Compose V2 syntax (no version field needed)

# Define volumes for data persistence
volumes:
  autogoal-data:
    driver: local
  app-data:
    driver: local
  pip-cache:
    driver: local

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the main application code
      - type: bind
        source: .
        target: /app
      # Mount the autogoal_repo
      - type: bind
        source: ./autogoal_repo
        target: /autogoal_repo
      # Shared data volumes
      - type: volume
        source: app-data
        target: /app/data
      - type: volume
        source: autogoal-data
        target: /autogoal_data
    working_dir: /app/src
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/app:/autogoal_repo
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - BUILD_ENVIRONMENT=development
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # GraphSVX explainability service
  graphsvx:
    build:
      context: .
      dockerfile: graphsvx.Dockerfile
    container_name: graphsvx
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: app-data
        target: /app/data
    working_dir: /graphsvx
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

# Network configuration
networks:
  app-network:
    name: text-to-graph-network
    driver: bridge
    driver_opts:
      encrypted: ''
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
