# Using Docker Compose V2 syntax (no version field needed)

# Define volumes for data persistence
volumes:
  autogoal-data:
    driver: local
  app-data:
    driver: local
  pip-cache:
    driver: local

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the main application code
      - type: bind
        source: .
        target: /app
      # Mount the autogoal_repo
      - type: bind
        source: ./autogoal_repo
        target: /autogoal_repo
      # Shared data volumes
      - type: volume
        source: app-data
        target: /app/data
      - type: volume
        source: autogoal-data
        target: /autogoal_data
    working_dir: /app/src
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/app:/autogoal_repo
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - BUILD_ENVIRONMENT=development
    networks:
      - app-network
    depends_on:
      - autogoal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

  # AutoGOAL optimization service built from source
  autogoal:
    build:
      context: .  # Use project root as context
      dockerfile: docker-compose/autogoal.Dockerfile  # Use our custom Dockerfile
      args:
        - BUILD_ENVIRONMENT=development
      cache_from:
        - autogoal/autogoal:core
    volumes:
      # Mount the main application code
      - type: bind
        source: .
        target: /app
      # Shared data volumes
      - type: volume
        source: app-data
        target: /app/data
      - type: volume
        source: autogoal-data
        target: /home/coder/autogoal-data
      # Cache for pip
      - type: volume
        source: pip-cache
        target: /home/coder/.cache/pip
    working_dir: /home/coder/autogoal
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/home/coder/autogoal:/app
      - BUILD_ENVIRONMENT=development
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    user: coder
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

# Network configuration
networks:
  app-network:
    name: text-to-graph-network
    driver: bridge
    driver_opts:
      encrypted: ''
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
