"""Unified CLI entry point for insight analytics routines."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List

from .utils import InsightFrame, load_insights

DEFAULT_OUTPUT_BASE = Path("outputs/analytics")

def _resolve_output_dir(args: argparse.Namespace) -> Path:
    """Determine and create the directory where artefacts will be stored."""
    if args.output_dir is not None:
        target = args.output_dir
    else:
        target = DEFAULT_OUTPUT_BASE / args.command
    target.mkdir(parents=True, exist_ok=True)
    return target

def _handle_structural_visualise(args: argparse.Namespace) -> None:
    """Compute correlation analytics and render structural heatmaps."""
    from . import structural_visualisation

    results = structural_visualisation.run_structural_visualisation(
        dataset=args.dataset,
        graph_type=args.graph,
        config_path=args.config,
        output_root=args.output_dir,
        significance_threshold=args.significance_threshold,
        create_clustered=not args.no_clustered,
    )

    summary = {
        "output_dir": str(results["output_dir"]),
        "analytics_csv": [str(path) for path in results.get("analytics_csv", [])],
        "heatmaps": [str(path) for path in results.get("heatmaps", [])],
        "difference_heatmaps": [str(path) for path in results.get("difference_heatmaps", [])],
        "difference_tables": [str(path) for path in results.get("difference_tables", [])],
        "significance_threshold": args.significance_threshold,
        "clustered": not args.no_clustered,
    }
    summary_path = Path(results["output_dir"]) / "structural_visualisation_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

def _handle_fidelity(args: argparse.Namespace) -> None:
    """Analyse fidelity drop distributions."""
    from . import fidelity_analysis

    output_dir = _resolve_output_dir(args)
    insight = load_insights(args.insight_paths)
    summary = fidelity_analysis.run_fidelity_analysis(insight, output_dir, args.group_key)
    (output_dir / "fidelity_analysis_summary.json").write_text(
        json.dumps(summary, indent=2),
        encoding="utf-8",
    )

def _handle_maskout(args: argparse.Namespace) -> None:
    """Measure maskout effects and correlations."""
    raise NotImplementedError("Maskout analytics disabled.")

def _handle_insertion(args: argparse.Namespace) -> None:
    """Compare insertion AUCs."""
    from . import insertion_auc_analysis

    output_dir = _resolve_output_dir(args)
    insight = load_insights(args.insight_paths)
    summary = insertion_auc_analysis.run_insertion_auc(insight, output_dir, args.group_key)
    (output_dir / "insertion_auc_summary.json").write_text(
        json.dumps(summary, indent=2),
        encoding="utf-8",
    )

def _handle_outliers(args: argparse.Namespace) -> None:
    """Detect outliers and produce cohort comparisons."""
    raise NotImplementedError("Outlier analytics disabled.")

def build_parser() -> argparse.ArgumentParser:
    """Construct the analytics CLI parser."""
    from . import structural_visualisation

    parser = argparse.ArgumentParser(
        description="Analytics toolkit for explanation insight exports.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    def add_common_arguments(subparser: argparse.ArgumentParser, include_group: bool = True) -> None:
        subparser.add_argument(
            "insight_paths",
            nargs="+",
            help="Insight JSON files generated by src.Insights.",
        )
        if include_group:
            subparser.add_argument(
                "--group-key",
                default="label",
                help="Column used for stratified analysis (default: label).",
            )
        subparser.add_argument(
            "--output-dir",
            type=Path,
            help="Directory where artefacts are written (default: outputs/analytics/<command>).",
        )

    # Structural analysis
    visualise_parser = subparsers.add_parser(
        "structural_visualise",
        help="Run structural graph analytics and render heatmaps for a dataset/graph pair.",
    )
    visualise_parser.add_argument(
        "--dataset",
        required=True,
        help="Dataset identifier (e.g. ag_news or sst2).",
    )
    visualise_parser.add_argument(
        "--graph",
        required=True,
        help="Graph flavour (constituency, syntactic, skipgrams, window).",
    )
    visualise_parser.add_argument(
        "--config",
        type=Path,
        default=structural_visualisation.DEFAULT_CONFIG_PATH,
        help="Path to structural config describing available datasets (default: configs/structural_analysis_config.json).",
    )
    visualise_parser.add_argument(
        "--output-dir",
        type=Path,
        help="Root directory for generated analytics (default: outputs/analytics/structural).",
    )
    visualise_parser.add_argument(
        "--significance-threshold",
        type=float,
        help="Absolute correlation difference threshold to highlight in difference heatmaps.",
    )
    visualise_parser.add_argument(
        "--no-clustered",
        action="store_true",
        help="Skip clustered difference heatmap generation.",
    )
    visualise_parser.set_defaults(func=_handle_structural_visualise)

    # Fidelity
    fidelity_parser = subparsers.add_parser(
        "fidelity",
        help="Study fidelity drops and identify extreme subsets.",
    )
    add_common_arguments(fidelity_parser)
    fidelity_parser.set_defaults(func=_handle_fidelity)

    # Insertion AUC
    insertion_parser = subparsers.add_parser(
        "insertion",
        help="Summarise insertion AUC distributions.",
    )
    add_common_arguments(insertion_parser)
    insertion_parser.set_defaults(func=_handle_insertion)

    return parser

def main(argv: List[str] | None = None) -> int:
    """Dispatch analytics subcommands."""
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)
    return 0

if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
